### ISSUE TITLE
docker pull fail ？

### ISSUE THREAD

**Issue by cyrusmaster** [kerberos-io/agent#100]
## I always get an error when I try to deploy Docker, even with a proxy

What's the solution?

![image](https://github.com/kerberos-io/agent/assets/45968542/6c915ae9-4b29-407c-9ecc-9c41392175f7)

**Comment by cedricve** [comment]
Hmm not sure, but looks something on your end?

<img width="879" alt="Screenshot 2023-05-10 at 08 41 14" src="https://github.com/kerberos-io/agent/assets/1546779/f5293c51-6f45-4348-85bf-fa6d46da1e53">
