### ISSUE TITLE
Docker: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by SiriusFuenmayor** [kerberos-io/agent#112]
Greetings, 

I am trying to install the docker image of Kerberos Agent on my Raspberry Pi 3 Model A+ with the command

`docker run --network=host --name mycamera -d --restart=always kerberos/agent:latest`

But I get the error:

`Docker: no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by cedricve** [comment]
We had an issue with the latest build. This should be fixed now, can you try again @SiriusFuenmayor ?

**Comment by SiriusFuenmayor** [comment]
Hi,I was able to pull the image after the changes. Thank you
