### ISSUE TITLE
is Commercial Support still active?

### ISSUE THREAD

**Issue by ilhay** [kerberos-io/agent#116]
Hello,

I'm so sorry to post here, I try to reach a support@kerberos.io and Zendesk many times but do not get response.
Just looking to purchase Enterprise 'Self-Hosted' Plan. Pls contact me back.

Thank you.

**Comment by cedricve** [comment]
Hey @ilhay, if you reach out to [support@kerberos.io](mailto:support@kerberos.io) someone should come back to you. Can you send directly to me cedric@kerberos.io?

**Comment by ilhay** [comment]
Hello,

I try to email to support@kerberos.io and submit a ticket via Zendesk. Zero Response.
How I just emailed to cedric@kerberos.io. Have you recevied it?

Thanks.
