### ISSUE TITLE
impossible for me to display the zone of interest

### ISSUE THREAD

**Issue by rudak** [kerberos-io/agent#118]
impossible for me to display the zone of interest, the screen remains black as if it couldn't find my camera even though it does (everything else works fine).
![2023-09-28_19-01](https://github.com/kerberos-io/agent/assets/604478/82ce9b8c-23a0-4dfb-bcf6-d87c1c210b4d)

**Comment by cedricve** [comment]
@rudak  can you attach the container logs please?

**Comment by cedricve** [comment]
Might because of the continuous recording mode, which hided the live stream in previous versions. This is now fixed in latest version. Closing for the time being.
