### ISSUE TITLE
Issue while verifying the camera settings: invalid Content-Base

### ISSUE THREAD

**Issue by CaptainCommuter** [kerberos-io/agent#132]
In the latest version of the agent when verifying the connection, the error "Something went wrong while verifying the camera settings: invalid Content-Base" occurs. 
This works OK with the November docker release and is running on Raspberry Pi and a S3VC IP camera using H264

**Comment by cedricve** [comment]
Thanks for reporting @CaptainCommuter, we are using a new RTSP library. Which camera are you using?

**Comment by cedricve** [comment]
can you share the RTSP url you are using? Are there other RTSP urls you can test out?

**Comment by CaptainCommuter** [comment]
Thanks for responding. The camera is a generic one from SV3C (www.sv3c.com) A series and the RTSP urls are:
rtsp://ipcam01/stream0 for the main stream and
rtsp://ipcam01/stream1 for the sub-stream.
None work and unfortunately that's all there is.

**Comment by cedricve** [comment]
The error thrown happens here: https://github.com/bluenviron/gortsplib/blob/main/client.go#L73-L88
I expect the RTSP url is not able to be parsed with our new library. Can you share the full log?
    
    if len(cb) != 1 {
	    return nil, fmt.Errorf("invalid Content-Base: '%v'", cb)
    }
    
    ret, err := base.ParseURL(cb[0])
    if err != nil {
	    return nil, fmt.Errorf("invalid Content-Base: '%v'", cb)
    }

I'm wondering if you use any special characters in the password? The RTSP url should work with following format (regex).
https://github.com/bluenviron/gortsplib/blob/main/pkg/base/url.go#L18-L45

**Comment by cedricve** [comment]
Ok that's great news, but it should work without password as well (not advised though).
