### ISSUE TITLE
Not sure how to connect camera

### ISSUE THREAD

**Issue by RickAndTired** [kerberos-io/agent#141]
I'm not sure what I'm doing wrong, I have this rtsp url that I've tested and works in other NVR servers:
`rtsp://192.168.1.160:1935/`

I get this error when using the rtsp url above:
`Something went wrong while verifying the camera settings: invalid Content-Base: '[192.168.1.160:1935/]'`

Happens in both Kerberos docker, snap, and static binary - Ubuntu 24.04 and Debian 12

**Comment by RickAndTired** [comment]
> You could try `rtsp://user:password@192.168.1.xxx`

This one doesn't work either

**Comment by cedricve** [comment]
@RickAndTired  what is the camera / model / brand you are using?

**Comment by RickAndTired** [comment]
I was using an Android phone with the app RTSP Camera Server Pro.

I was only using it so I could test out Kerberos, but since it didn't work I ended up buying an IP camera.

**Comment by cedricve** [comment]
Thanks for the update @RickAndTired!
