### ISSUE TITLE
Creating designs in Figma

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/agent#15]
Started creating some designs in Figma, for the different pages. Any help is welcome! You can always give feedback on the designs by opening below link, and creating an account at Figma, once signed in you can write comments.

https://www.figma.com/file/PpjFz2GGX6ZaWyIzef6mqT

- [x] Create Login page
https://www.figma.com/file/PpjFz2GGX6ZaWyIzef6mqT/Open-Source?node-id=57%3A0

- [x] Create Home page
- [x] Create Media page
- [x] Create Settings page
- [x] Create Profile page

**Comment by cedricve** [comment]
Currently working on the login page: figma.com/file/PpjFz2GGX6ZaWyIzef6mqT/Web?node-id=57%3A0

**Comment by cedricve** [comment]
Designs are done, thanks @AllienWorks. All designs can be viewed here: https://www.figma.com/file/msuYC6sv2cOCqZeDtBxNy7/NEW-Kerberos.io-Apps?node-id=1%3A2

**Comment by AllienWorks** [comment]
Hello everybody,

if you're interested to play with the latest prototype, here's the latest version:

## [Latest Kerberos.io Open Source Agent prototype](https://www.figma.com/proto/msuYC6sv2cOCqZeDtBxNy7/Kerberos.io-Apps?node-id=1%3A1464&viewport=768%2C361%2C0.16784118115901947&scaling=min-zoom&page-id=1%3A2%3Ffuid%3D449684443467913607)

It's a clickable prototype, mimicking the real behaviour. Of course it's quite limited, but it will probably give you a better feeling of the Open Source Agent anyway :)
