### ISSUE TITLE
Continuous recording with timestamped filenames

### ISSUE THREAD

**Issue by draco2003** [kerberos-io/agent#20]
I have been investigating a handful of different RTSP -> Stream + File systems and this is one is very nice. 

Is there a set of conditions that I can configure to enable to record all video from an IP based camera not just motion triggered events?

**Comment by cedricve** [comment]
hey @draco2003, yes this is in kerberos enterprise, and will be available in the next open source version (V3).

**Comment by olokos** [comment]
Latest Agent open Source version does have an option in config that allows enabling continuous mode. 
I suppose this issue can be closed

**Comment by cedricve** [comment]
Correct this is now supported!
