### ISSUE TITLE
CORS related deprecation (May 2021)

### ISSUE THREAD

**Issue by nargetdev** [kerberos-io/agent#23]
I noticed I was getting a CORS rejection...
i.e. web origin `localhost:3000` rejects usage of machinery origin `localhost:8080`

..and then I saw a deprecation dated for today's date regarding CORS

Here's the deprecation message:

scheduler.development.js:298 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

**Comment by ElomAkaba** [comment]
@nargetdev how did you come around this issue?

**Comment by cedricve** [comment]
This is related to the old agent, we currently have a BETA released for this repo (the new Kerberos Agent)
