### ISSUE TITLE
Agent not displaying rpi camera on pi4 b and kios issues

### ISSUE THREAD

**Issue by tpolitza** [kerberos-io/agent#31]
Raspberry Pi 4 Model B 4GB
KiOS will not run without replacing fixup4.dat and start4.elf with Bullseye files.
Once running, KiOS dashboard does not show a stream of the rpi camera (v 2.1)
Camera confirmed working on rpi OS.
I'm guessing this has to do with the change in the board architecture and camera commands.
Do you intend to release a Pi 4 B/rpi camera compatible version?

**Comment by olokos** [comment]
You can download the latest release version of RaspberryOS, personally I use 32 bit for compatibility reasons on Pi4B and HQ Camera.

Current way to use it with Agent is by using aler9's rtsp-simple-server docker and then passing on Rpi Camera to agent as an IP Camera.

There are plans to support RpiCamera natively, but for that to happen we need to wait for rtsp simple stream update to support native camera.
