### ISSUE TITLE
Something went wrong while verifying storage credentials: {"code":401,"message":"cookie token is empty"}

### ISSUE THREAD

**Issue by nurio-felix** [kerberos-io/agent#42]
![error](https://user-images.githubusercontent.com/110847281/188773673-f0231767-b2d4-4485-8c87-b5e1edb3b4dd.jpg)

Please, it is possible check this?

**Comment by cedricve** [comment]
amazing you are already using it..
Can you verify if the endpoint is valid? You dont need to add the suffix "storage" anymore.

Kind regards,
Verstraeten Cédric

**Comment by cedricve** [comment]
@nurio-felix do you need more help on this?

**Comment by nurio-felix** [comment]
Hi, thx for your reply. 
Is working fine now.
The error was in the vault, Accounts should have "*" in directory

![vault](https://user-images.githubusercontent.com/110847281/189179180-5a49508f-2c17-4fe0-a0bf-2d6adce745b4.jpg)

Now I am having another error in "Continuous recording".
I will open new issue for this.

**Comment by cedricve** [comment]
thanks!
