### ISSUE TITLE
No Live View and Motion Dectetions when Continuous recording enabled

### ISSUE THREAD

**Issue by nurio-felix** [kerberos-io/agent#50]
Hello,

When Continuous recording is enabled, Live View is not working for me, also I think Motion Dectetions it should remain active even is Continuous recording is ON.

![agent-outdoor](https://user-images.githubusercontent.com/110847281/190528730-85b320b6-22c3-4455-a7ee-1db269001be1.jpg)

**Comment by cedricve** [comment]
Correct we disabled motion on continuous recording for performance. We might need to make this adjustable so we can combine both.

Motion detection is linked to the live view as we are using the motion images for the live stream.

Lets make this an enhancement.

Kind regards,
Verstraeten Cédric

**Comment by cedricve** [comment]
This is now fixed, we are using another method (websockets) to send over the MJPEGs. This now works for both settings (motion or continuous).
