### ISSUE TITLE
When used a different approach the agent crashes

### ISSUE THREAD

**Issue by olokos** [kerberos-io/agent#68]
Below are logs provided for this issue
https://pastebin.com/Lir44J3g

This happens when booting the OS and apparently now agent crashes completely if the stream isn't yet ready.
Previously the agent handled nicely the situation where the stream was not yet ready, now it crashes instead.

I think it would be nice to resolve this so just about any approach works perfectly, even if the suggested one is truly the best one.

**Comment by cedricve** [comment]
Correct this should have be fixed now, this bug was introduced with the new streaming feature through websockets. Please reopen if you find this is not resolved. `docker pull kerberos/agent` to get latest release.

**Comment by olokos** [comment]
I can confirm this is now fixed and working just as good as before!
Thank You!
