### ISSUE TITLE
Tapo Camera Audio Support

### ISSUE THREAD

**Issue by harpyeagle** [kerberos-io/agent#77]
Hi @cedricve 

I am using the agent to record birds in a number of nestboxs. I am also signed up to the Hub as the analytics is a great addition to quickly see the activity during the day. The issue I have is no audio, the rtsp stream contains audio and I have verified this on VLC player but the agent / hub are not picking this up. Is there a setting I am missing to enable audio on the recording.

Thanks John

**Comment by cedricve** [comment]
hey there @harpyeagle which audio codec do you have selected for your Tapo Camera?

**Comment by harpyeagle** [comment]
Hi @cedricve 

Based on VLC it is it is PCM ALAW

<img width="494" alt="Screenshot 2023-02-13 at 20 08 10" src="https://user-images.githubusercontent.com/16882283/218564004-ae695e4b-e85b-4d17-90b7-26d8656f667c.png">

**Comment by cedricve** [comment]
Is there an option to modify to PCM_MULAW?

**Comment by cedricve** [comment]
Apologies modify to AAC (this is required for MP4). We are still working on audio for livestream, but you can expect this enhancement soon. AAC audio is already supported for recordings.

**Comment by cedricve** [comment]
PCM_ALAW is now supported in live streaming, still needs transcoding to AAC to work in MP4.

**Comment by cedricve** [comment]
Bi-directional audio is now added, but it lacks support (incoming) for Tapo cameras as they don't support the ONVIF backchannel method. To transfer audio through the livestream on Kerberos Hub, the camera stream needs to support (and has enabled) PCM_ULAW. To record audio in a MP4 file (recording) the audio needs to be set to AAC.

At the moment we are working on transcoding from AAC -> PCM_ULAW and AAC -> PCM_ULAW to make sure we can support both scenarios.
