### ISSUE TITLE
Unable to update mounted config.json

### ISSUE THREAD

**Issue by b3ddy** [kerberos-io/agent#94]
I'm having a similar issue to the currently open issue (https://github.com/kerberos-io/agent/issues/63) regarding pixel region not updating in the mounted config. However, with my mounted config none of the settings are saving from the configuration panel. Total noob here, was I supposed to give the container permissions for it to be allowed to update the config.json on the host machine?

**Comment by cedricve** [comment]
Not sure if this is linked -> https://github.com/kerberos-io/agent/issues/80

**Comment by b3ddy** [comment]
Thanks for the link, I'll test it asap and let you know.

**Comment by b3ddy** [comment]
Hey @cedricve, 

Thanks for the link! My user owned the directory, but telling the container to use the host credentials seems to have fixed it. 

Ran the container with these settings and seems to be saving properly now. 

`docker run -p 80:80 --name mycamera \
-v /home/user/agent/config:/home/agent/data/config \
-v /home/user/agent/recordings:/home/agent/data/recordings \
--user 1000:1000 \
-d --restart=always kerberos/agent:latest
`

**Comment by instantdreams** [comment]
Makes sense. I'll try that if I spin up another kerberos agent.
